### ISSUE TITLE
请问怎样修改能不隐藏标题栏

### ISSUE THREAD

**Issue by liugh-dev** [UserZYF/blue-dog#9]
前端的东西我不大懂，但是这个主题是真的舒服，就是隐藏标题栏之后用起来偶尔有点不便，请问有简单的修改办法让它不隐藏标题栏吗？

**Comment by UserZYF** [comment]
```css
/* blue-dog主题取消隐藏顶栏 */
.toolbar {
    margin-bottom: 0 !important;
    opacity: 1 !important;
    transition: none;
    transform: none;
    background-color: #f3f5f7 !important;
}
```
复制后粘贴到`设置-外观-代码片段`中即可（记得点击启用按钮）
